---
title: "Compute Potential"
vignette: >
  %\VignetteIndexEntry{Compute Potential}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---


```{r}
#| label: setup
devtools::load_all("../")
```

(replace with `library(biodt.recreation)` when finished developing)

## Load/create a persona

```{r}
persona_file <- system.file("extdata", "example_personas.csv", package = "biodt.recreation")
persona <- load_persona(persona_file, "Hard_Recreationalist")
persona
```

## Select an area of interest

```{r}
bbox_file <- system.file("extdata", "shapefiles", "Bush", "Bush.shp", package = "biodt.recreation")
bbox <- terra::ext(terra::vect(bbox_file))
bbox
```

## Compute a single component

```{r}
fips_n <- compute_fips_n(persona, bbox)
terra::plot(fips_n)
```

```{r}
water <- compute_component("Water", persona, bbox)
terra::plet(water)
```

## Compute all layers

```{r}
layers <- compute_potential(persona, bbox)
names(layers)

terra::plot(layers[["Recreational_Potential"]])
```
