---
title: Personas
vignette: >
  %\VignetteIndexEntry{Compute Potential}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---


```{r}
#| label: setup
devtools::load_all("../")
```

(replace with `library(biodt.recreation)` when finished developing)

## Load the preset personas

```{r}
persona_file <- get_preset_persona_file()

persona_df <- read_persona_csv(persona_file)

persona_df
```


## Load a single persona

```{r}
hr_persona <- load_persona(persona_file, "Hard_Recreationalist")
hr_persona
```

## Save a new persona

```{r}
# create a temporary file to save
new_persona_file <- tempfile(fileext = ".csv")

# Save a copy of the Hard_Recreationalist persona
save_persona(hr_persona, new_persona_file, "Hard_Copy")

# Check the file contents
read_persona_csv(new_persona_file)

# Create a random new person
feature_names <- load_config()[["Name"]]
random_persona <- stats::setNames(
    sample(0:10, size = 87, replace = TRUE),
    feature_names
)

# Append it to the file
save_persona(random_persona, new_persona_file, "Random")

# Check the file contents
read_persona_csv(new_persona_file)

unlink(new_persona_file)
```
